Update backup_etc.erb

diff --git a/deployment_scripts/backup/modules/backup_etc/templates/backup_etc.erb b/deployment_scripts/backup/modules/backup_etc/templates/backup_etc.erb
--- a/deployment_scripts/backup/modules/backup_etc/templates/backup_etc.erb
+++ b/deployment_scripts/backup/modules/backup_etc/templates/backup_etc.erb
@@ -11,55 +11,44 @@ DEST="${BACKUP_DIR}/$SUFFIX/"
 NUM_TO_KEEP=<%= @numtokeep %>
 LCK_FILE=`basename $0`.lck
 
-function pid {
-  # Am I Running
-  if [ -f "${LCK_FILE}" ]; then
-    MYPID=`head -n 1 $LCK_FILE`
-    while [ -n "`ps -p ${MYPID} | grep ${MYPID}`" ]
-    do
-      echo `basename $0` is already running [$MYPID]
-      exit
-    done
-  fi
-  echo $$ > $LCK_FILE
-}
-
-function make_dir_if_not_exist {
-  if [ -d $DEST ]; then
-    echo "Destination folder already exists"
-  else
-    echo "Creating folder $DEST"
-    mkdir -p $DEST
-  fi
-}
-
-function remove_old_data {
-  ssh -i $SSH_KEY -o StrictHostKeyChecking=no root@${MASTER_IP} rm -f  nodes_info.tar.gz
-
-  echo "Clearing earliest backup directories..."
-  NUM_LOCAL_BACKUPS=`ls -l $BACKUP_DIR | grep '^d' | wc -l`
-  while [ $NUM_LOCAL_BACKUPS -gt $NUM_TO_KEEP ]
+# Am I Running
+if [ -f "${LCK_FILE}" ]; then
+  MYPID=`head -n 1 $LCK_FILE`
+  while [ -n "`ps -p ${MYPID} | grep ${MYPID}`" ]
   do
-    EARLIEST_BACKUP=`ls -tr $BACKUP_DIR | head -1`
-    echo "Deleting $EARLIEST_BACKUP..."
-    rm -rf "$BACKUP_DIR/$EARLIEST_BACKUP"
-    NUM_LOCAL_BACKUPS=`ls -l $BACKUP_DIR | grep '^d' | wc -l`
+    echo `basename $0` is already running [$MYPID]
+    exit
   done
-}
-
-function check_return_code {
-  BACKUP_RETURN_CODE=$?
-
-  if [[ $BACKUP_RETURN_CODE != 0 ]]; then
-    echo "There was an error backing up the databases. Return code was $BACKUP_RETURN_CODE. Please check log file."
-    exit $BACKUP_RETURN_CODE
-  fi
-}
+fi
+echo $$ > $LCK_FILE
 
 
-pid
-make_dir_if_not_exist
+if [ -d $DEST ]; then
+  echo "Destination folder already exists"
+else
+  echo "Creating folder $DEST"
+  mkdir -p $DEST
+fi
+
 ssh -i $SSH_KEY -o StrictHostKeyChecking=no root@${MASTER_IP} /etc/puppet/modules/osnailyfacter/modular/backup/get_node_info.sh
-check_return_code
+
+BACKUP_RETURN_CODE=$?
+
+if [ $BACKUP_RETURN_CODE != 0 ]; then
+  echo "There was an error backing up the databases. Return code was $BACKUP_RETURN_CODE. Please check log file."
+  exit $BACKUP_RETURN_CODE
+fi
+
 scp -i $SSH_KEY root@${MASTER_IP}:nodes_info.tar.gz $DEST
-remove_old_data
+
+ssh -i $SSH_KEY -o StrictHostKeyChecking=no root@${MASTER_IP} rm -f  nodes_info.tar.gz
+
+echo "Clearing earliest backup directories..."
+NUM_LOCAL_BACKUPS=`ls -l $BACKUP_DIR | grep '^d' | wc -l`
+while [ $NUM_LOCAL_BACKUPS -gt $NUM_TO_KEEP ]
+do
+  EARLIEST_BACKUP=`ls -tr $BACKUP_DIR | head -1`
+  echo "Deleting $EARLIEST_BACKUP..."
+  rm -rf "$BACKUP_DIR/$EARLIEST_BACKUP"
+  NUM_LOCAL_BACKUPS=`ls -l $BACKUP_DIR | grep '^d' | wc -l`
+done
